version: '3'
services:
  web:
    container_name: sistem-informasi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: repository
      MYSQL_USER: web
      MYSQL_PASSWORD: web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: verysecret
